version: "3.9"

services:
  n8n:
    environment:
      # Comma‑separated bot IDs for workflow isolation
      BOT_IDS: "${BOT_IDS}"
      POSTGRES_MULTIPLE_SCHEMAS: "true"
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "${N8N_USER}"
      N8N_BASIC_AUTH_PASSWORD: "${N8N_PASS}"
      N8N_ENCRYPTION_KEY: "${N8N_ENCRYPTION_KEY}"
      N8N_HOST: "n8n"
      N8N_PORT: 5678
    ports:
      - "5678:5678"
    volumes:
      # Shared configs for all bots
      - ./bot-configs:/bot-configs:rw
      # Persistent n8n data
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
      - qdrant
    restart: unless-stopped

  postgres:
    environment:
      POSTGRES_MULTIPLE_SCHEMAS: "true"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  n8n_data:
  postgres_data:
  qdrant_data:
